Update bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -62,18 +62,29 @@ for tool in $tools
 do
 	if ! type -p $tool > /dev/null
 	then
-		echo "FAILED to find build tool '$tool'!"
-		echo
-		echo BOOTSTRAP FAILED!
-		echo
-		exit 1
+		for d in $HOME/bakefile/bin
+		do
+			TOOL_BIN="$d"
+			if [ -e "$TOOL_BIN/$tool" ] ; then break ; fi
+		done
+		
+		if [ -e "$TOOL_BIN/$tool" ] 
+		then
+			echo
+		else
+			echo "FAILED to find build tool '$tool'!"
+			echo
+			echo BOOTSTRAP FAILED!
+			echo
+			exit 1
+		fi
 	fi
 done
 
 # Find location of Bakefile's stock M4 autoconf macros
 for d in /usr/share/aclocal /usr/local/share/aclocal \
 	'/c/Program Files (x86)/Bakefile/autoconf' \
-	$ROOTDIR
+	$HOME/bakefile/share
 do
 	BAKEFILE_M4="$d"
 	if [ -e "$BAKEFILE_M4/bakefile.m4" ] ; then break ; fi
